FROM openjdk:8-jre

MAINTAINER DevName <dev.txt@dev.com>

USER root

ENV ROOT_DIR /app

ENV FUll_APP_NAME app-service*.jar
ENV APP_NAME app-service.jar
ENV APP_HOME ${ROOT_DIR}/${APP_NAME}

ENV APP_CONFIG_DIR ${ROOT_DIR}/config
ENV APP_LOG_DIR ${ROOT_DIR}/config

COPY ./target/${FUll_APP_NAME} ${APP_HOME}

COPY entrypoint.bash ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

RUN $JAVA_HOME/bin/keytool -import -trustcacerts -file cluster-uat.cert -alias prod_cluster -keystore /usr/local/openjdk-8/lib/security/cacerts -storepass changeit -noprompt

ENTRYPOINT ["/bin/sh", "-c", "./entrypoint.sh"]
